spring.application.name=moattravel_1
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/moat_trabel1_db
spring.datasource.username=root
spring.datasource.password=k1n07g1p00h
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.encoding=utf-8
spring.sql.init.mode=always
spring.servlet.multipart.max-file-size=5MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kino7gi.pooh@gmail.com
spring.mail.password=blsq pzko mekc eljl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true