spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/samuraitraveldb
spring.datasource.username=root
spring.datasource.password=k1n07g1p00h
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.encoding=utf-8
spring.sql.init.mode=always
spring.servlet.multipart.max-file-size=5MB
spring.mail.host=smtp.gmail.com
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.mail.port=587
spring.mail.test-connection=false
spring.mail.username=kino7gi.pooh@gmail.com
spring.mail.password=アプリパスワード
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

