spring.application.name=moattravel
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/moat_travel_db
spring.datasource.username=root
spring.datasource.password=k1n07g1p00h
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.encoding=utf-8
spring.sql.init.mode=always
#アップロードできるファイルのサイズを変更することができる
spring.servlet.multipart.max-file-size=5MB
# セッションの永続化（保存）を無効にする
server.servlet.session.persistence=false